//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardiyaTakipDefteri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POLY_QDMSEntities : DbContext
    {
        public POLY_QDMSEntities()
            : base("name=POLY_QDMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vardiya_Kullanici> Vardiya_Kullanici { get; set; }
        public virtual DbSet<Vardiya_Resim> Vardiya_Resim { get; set; }
        public virtual DbSet<Vardiya_TrafoKmprsr> Vardiya_TrafoKmprsr { get; set; }
        public virtual DbSet<Vardiya_Bolum> Vardiya_Bolum { get; set; }
        public virtual DbSet<Vardiya_BolumMakine> Vardiya_BolumMakine { get; set; }
        public virtual DbSet<Vardiya_Defter> Vardiya_Defter { get; set; }
        public virtual DbSet<Vardiya_Saat> Vardiya_Saat { get; set; }
        public virtual DbSet<Vardiya_DefterAna> Vardiya_DefterAna { get; set; }
    }
}
