//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardiyaTakipDefteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vardiya_TrafoKmprsr
    {
        public int ID { get; set; }
        public Nullable<int> TrafoNo1 { get; set; }
        public Nullable<int> TrafoNo2 { get; set; }
        public Nullable<int> TrafoNo3 { get; set; }
        public Nullable<int> TrafoNo4 { get; set; }
        public Nullable<int> TrafoNo5 { get; set; }
        public Nullable<int> TrafoNo6 { get; set; }
        public Nullable<int> TrafoNo7 { get; set; }
        public string YedekKompresor { get; set; }
        public string CalisanSogutmaIsitma { get; set; }
        public Nullable<int> VardiyaDefteriAnaId { get; set; }
    
        public virtual Vardiya_DefterAna Vardiya_DefterAna { get; set; }
    }
}
