//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardiyaTakipDefteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vardiya_Saat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vardiya_Saat()
        {
            this.Vardiya_DefterAna = new HashSet<Vardiya_DefterAna>();
        }
    
        public int ID { get; set; }
        public string VardiyaSaati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vardiya_DefterAna> Vardiya_DefterAna { get; set; }
    }
}
