//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardiyaTakipDefteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vardiya_DefterAna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vardiya_DefterAna()
        {
            this.Vardiya_Defter = new HashSet<Vardiya_Defter>();
            this.Vardiya_TrafoKmprsr = new HashSet<Vardiya_TrafoKmprsr>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string VardiyaAmiri { get; set; }
        public Nullable<bool> TamamlandiMi { get; set; }
        public string VardiyaAmirYardimcisi { get; set; }
        public string VardiyaSaati { get; set; }
        public Nullable<int> VardiyaSaatiId { get; set; }
        public Nullable<int> VardiyaSaatDeger { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vardiya_Defter> Vardiya_Defter { get; set; }
        public virtual Vardiya_Saat Vardiya_Saat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vardiya_TrafoKmprsr> Vardiya_TrafoKmprsr { get; set; }
    }
}
