//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardiyaTakipDefteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vardiya_BolumMakine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vardiya_BolumMakine()
        {
            this.Vardiya_Defter = new HashSet<Vardiya_Defter>();
        }
    
        public int MakineID { get; set; }
        public string Makineler { get; set; }
        public Nullable<int> BolumID { get; set; }
    
        public virtual Vardiya_Bolum Vardiya_Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vardiya_Defter> Vardiya_Defter { get; set; }
    }
}
